const gameSeq = [];   // pattern generated by the game
const userSeq = [];   // pattern clicked by the user
const btns = ["btn1", "btn2", "btn3", "btn4"];

let started = false;
let level = 0;

const gameLevel = document.querySelector("h2");

/*  start game on first keypress  */
function startGame() {
    if (!started) {
        started = true;
        levelUp();
    }
}

function flash(btn) {
    btn.classList.add("flash");
    setTimeout(() => btn.classList.remove("flash"), 300);
}

function levelUp() {
    userSeq.length = 0;
    level++;
    gameLevel.textContent = `Level ${level}`;

    let randomIdx = Math.floor(Math.random() * 4); // 0-3
    let randomColor = btns[randomIdx];
    let randomBtn = document.querySelector(`#${randomColor}`);

    gameSeq.push(randomColor);
    console.log(gameSeq);
    flash(randomBtn);
}


function checkAns(idx) {

    if (userSeq[idx] === gameSeq[idx]) {
        console.log("same value");
        if(userSeq.length == gameSeq.length){
            setTimeout(levelUp, 500);
        }
        } else {
            gameLevel.innerHTML = `Game Over! your score :${level}<br> Press any key to start.`;
            document.querySelector('body').style.backgroundColor = "red";
            setTimeout(function(){
                document.querySelector('body').style.backgroundColor = "white";
            },150)
            reset();
        }
}


function handleClick() {
    let userBtn = this;
    flash(userBtn);

    let userColor = userBtn.getAttribute("id"); // ← correct capital “A”
    userSeq.push(userColor);

    console.log(`Clicked: ${userColor}`);
    checkAns(userSeq.length-1);
}

/*  attach listeners  */
document.addEventListener("keypress", startGame);

let allBtns = document.querySelectorAll(".btn");
for (let btn of allBtns) {
    btn.addEventListener("click", handleClick);
}

function reset(){
    started = false;
    gameSeq = [];
    userSeq = [];
    level = 0;
}